server:
  port: 3002
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:3000/eureka/
      
spring:
  application:
    name: service-feign
  cloud:
    config:
      label: master
      profile: dev
      uri: config-server    
feign: 
  hystrix: 
    enabled: true